train_batch_size: 32
test_batch_size: 32
# num_workers: 8
dataset: 'oxford102'
datapath: ''
out_dir: '../ckpts'

model: ResNet50
model_kwargs:
  num_classes: 102

pred_module:
  optimizer: Adam
  lr: 0.001

trainer:
  gpus: 1
  num_nodes: 1
  max_epochs: 5
